### ISSUE TITLE
Wont join

### ISSUE THREAD

**Issue by muaawiyahtucker** [payjoin/nolooking#110]
I get this issue/message every time sparrow wallet tries to connect the payjoin with the payjoin instance on an umbrel

Scheduler error: scheduler error: Lnd(Generic(Status { code: Unknown, message: "CSV delay too large: 480, max is 288", metadata: MetadataMap { headers: {"content-type": "application/grpc"} }, source: None }))

Any idea what it means?

**Comment by DanGould** [comment]
I believe this is an issue with your peer. Either configure your node to accept higher CSV or try another one.

https://bitcoin.stackexchange.com/questions/116949/lnd-seems-to-ignore-csv-delay-settings-when-opening-a-channel

quick gpt4 query response:

> When you try to open a Lightning Network channel and get the error "CSV Delay too large," it means the counterparty you're trying to open the channel with has set their "to_self_delay" to a value that's considered too high by your node. This parameter is also known as the CSV (CheckSequenceVerify) delay.
>
> In the Lightning Network, the "to_self_delay" is a security parameter that's set when a channel is created. It specifies the number of blocks the other party must wait before they can spend their funds if they broadcast a revoked commitment transaction. The purpose of this delay is to provide the counterparty enough time to punish the malicious party by taking all the funds in the channel.
>
> Here are a few troubleshooting steps you could take:
>
> - Try a different peer: If the CSV delay is too high, it could be an indication that the peer has set their "to_self_delay" to an unusually large value. Trying to open a channel with a different peer could circumvent this issue.
>
> - Adjust your node's CSV Delay tolerance: Each node can set its own maximum acceptable CSV delay. If you're running your own node, you could potentially adjust this tolerance. However, keep in mind that this is a security parameter, and increasing it would mean a longer wait in case of a channel dispute.
>
> - Communicate with the peer: If the peer you're trying to connect with is known to you, you could try reaching out to them to inquire about their CSV delay setting. It's possible that they could adjust it to allow the channel to be created.
>
> Remember, it's crucial to take into consideration the implications of adjusting these settings and the potential risk involved. The CSV delay is a crucial security feature to prevent fraudulent activity on the network, so any changes should be carefully considered.
